export const SET_CHART_LOADING_STATUS = 'chart/SET_LOADING_STATUS'
export const SET_CHART_ERROR = 'chart/SET_ERROR'
export const FETCH_CHART_DATA = 'chart/FETCH_DATA'
export const SET_CHART_DATA = 'chart/SET_DATA'
export const UPDATE_CHART_DATA = 'chart/UPDATE_DATA'
